stages:
  - analyze
  - test

variables:
  FLUTTER_CHANNEL: "stable"

image: ghcr.io/cirruslabs/flutter:latest

before_script:
  - flutter --version
  - cd ai-tutoring-platform-5516-5525/ai_tutoring_app_frontend

analyze:
  stage: analyze
  script:
    - flutter pub get
    - flutter analyze

test:
  stage: test
  script:
    - flutter test --machine
