include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: false

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - android/**/build/**
    - ios/**/build/**
    - web/**/build/**
    - linux/**/build/**
    - macos/**/build/**
    - windows/**/build/**
