trigger:
  - main
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - task: FlutterInstall@0
    inputs:
      channel: 'stable'
  - script: flutter pub get
    workingDirectory: ai-tutoring-platform-5516-5525/ai_tutoring_app_frontend
    displayName: 'flutter pub get'
  - script: flutter analyze
    workingDirectory: ai-tutoring-platform-5516-5525/ai_tutoring_app_frontend
    displayName: 'flutter analyze'
  - script: flutter test
    workingDirectory: ai-tutoring-platform-5516-5525/ai_tutoring_app_frontend
    displayName: 'flutter test'
