version: 2.1

orbs:
  flutter: circleci/flutter@1.2.0

jobs:
  analyze_and_test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - flutter/install:
          flutter-version: stable
      - run:
          name: flutter pub get
          command: |
            cd ai-tutoring-platform-5516-5525/ai_tutoring_app_frontend
            flutter pub get
      - run:
          name: flutter analyze
          command: |
            cd ai-tutoring-platform-5516-5525/ai_tutoring_app_frontend
            flutter analyze
      - run:
          name: flutter test
          command: |
            cd ai-tutoring-platform-5516-5525/ai_tutoring_app_frontend
            CI=true flutter test

workflows:
  analyze_test:
    jobs:
      - analyze_and_test
